// Countries in the quiz. Capitals, continents and map points come from Wikidata (CC0);
// shape = the country's id in world-atlas countries-50m (ISO 3166-1 numeric), or its name.
const COUNTRIES = [
  {"name": "United States", "code": "us", "level": "easy", "capital": "Washington, D.C.", "continent": "North America", "lon": -98.58, "lat": 39.83, "shape": "840"},
  {"name": "Canada", "code": "ca", "level": "easy", "capital": "Ottawa", "continent": "North America", "lon": -109.0, "lat": 56.0, "shape": "124"},
  {"name": "Mexico", "code": "mx", "level": "easy", "capital": "Mexico City", "continent": "North America", "lon": -102.0, "lat": 23.0, "shape": "484"},
  {"name": "United Kingdom", "code": "gb", "level": "easy", "capital": "London", "continent": "Europe", "lon": -2.0, "lat": 54.6, "shape": "826"},
  {"name": "France", "code": "fr", "level": "easy", "capital": "Paris", "continent": "Europe", "lon": 2.0, "lat": 47.0, "shape": "250"},
  {"name": "Germany", "code": "de", "level": "easy", "capital": "Berlin", "continent": "Europe", "lon": 10.0, "lat": 51.0, "shape": "276"},
  {"name": "Italy", "code": "it", "level": "easy", "capital": "Rome", "continent": "Europe", "lon": 12.5, "lat": 42.5, "shape": "380"},
  {"name": "Spain", "code": "es", "level": "easy", "capital": "Madrid", "continent": "Europe", "lon": -3.5, "lat": 40.2, "shape": "724"},
  {"name": "Japan", "code": "jp", "level": "easy", "capital": "Tokyo", "continent": "Asia", "lon": 136.0, "lat": 35.0, "shape": "392"},
  {"name": "China", "code": "cn", "level": "easy", "capital": "Beijing", "continent": "Asia", "lon": 103.45, "lat": 35.84, "shape": "156"},
  {"name": "Australia", "code": "au", "level": "easy", "capital": "Canberra", "continent": "Oceania", "lon": 133.0, "lat": -25.0, "shape": "036"},
  {"name": "Brazil", "code": "br", "level": "easy", "capital": "Brasília", "continent": "South America", "lon": -53.0, "lat": -14.0, "shape": "076"},
  {"name": "Russia", "code": "ru", "level": "easy", "capital": "Moscow", "continent": "Europe and Asia", "lon": 94.25, "lat": 66.42, "shape": "643"},
  {"name": "India", "code": "in", "level": "easy", "capital": "New Delhi", "continent": "Asia", "lon": 83.0, "lat": 22.8, "shape": "356"},
  {"name": "South Korea", "code": "kr", "level": "easy", "capital": "Seoul", "continent": "Asia", "lon": 128.0, "lat": 36.0, "shape": "410"},
  {"name": "South Africa", "code": "za", "level": "easy", "capital": "Pretoria, Cape Town, and Bloemfontein", "continent": "Africa", "lon": 24.0, "lat": -29.0, "shape": "710"},
  {"name": "Argentina", "code": "ar", "level": "easy", "capital": "Buenos Aires", "continent": "South America", "lon": -64.0, "lat": -34.0, "shape": "032"},
  {"name": "Turkey", "code": "tr", "level": "easy", "capital": "Ankara", "continent": "Europe and Asia", "lon": 36.0, "lat": 39.0, "shape": "792"},
  {"name": "Greece", "code": "gr", "level": "easy", "capital": "Athens", "continent": "Europe", "lon": 23.0, "lat": 38.5, "shape": "300"},
  {"name": "Norway", "code": "no", "level": "easy", "capital": "Oslo", "continent": "Europe", "lon": 10.68, "lat": 59.93, "shape": "578"},
  {"name": "Sweden", "code": "se", "level": "easy", "capital": "Stockholm", "continent": "Europe", "lon": 15.0, "lat": 61.0, "shape": "752"},
  {"name": "Switzerland", "code": "ch", "level": "easy", "capital": "Bern", "continent": "Europe", "lon": 8.23, "lat": 46.8, "shape": "756"},
  {"name": "Egypt", "code": "eg", "level": "easy", "capital": "Cairo", "continent": "Africa", "lon": 29.0, "lat": 27.0, "shape": "818"},
  {"name": "Saudi Arabia", "code": "sa", "level": "easy", "capital": "Riyadh", "continent": "Asia", "lon": 44.12, "lat": 23.72, "shape": "682"},
  {"name": "Israel", "code": "il", "level": "easy", "capital": "Jerusalem", "continent": "Asia", "lon": 35.0, "lat": 31.0, "shape": "376"},
  {"name": "Nigeria", "code": "ng", "level": "easy", "capital": "Abuja", "continent": "Africa", "lon": 8.0, "lat": 9.0, "shape": "566"},
  {"name": "Portugal", "code": "pt", "level": "easy", "capital": "Lisbon", "continent": "Europe", "lon": -9.18, "lat": 38.7, "shape": "620"},
  {"name": "Netherlands", "code": "nl", "level": "easy", "capital": "Amsterdam", "continent": "Europe", "lon": 4.88, "lat": 52.37, "shape": "528"},
  {"name": "New Zealand", "code": "nz", "level": "easy", "capital": "Wellington", "continent": "Oceania", "lon": 174.0, "lat": -41.2, "shape": "554"},
  {"name": "Cuba", "code": "cu", "level": "easy", "capital": "Havana", "continent": "North America", "lon": -79.5, "lat": 22.0, "shape": "192"},
  {"name": "Poland", "code": "pl", "level": "medium", "capital": "Warsaw", "continent": "Europe", "lon": 19.0, "lat": 52.0, "shape": "616"},
  {"name": "Ukraine", "code": "ua", "level": "medium", "capital": "Kyiv", "continent": "Europe", "lon": 32.0, "lat": 49.0, "shape": "804"},
  {"name": "Belgium", "code": "be", "level": "medium", "capital": "Brussels", "continent": "Europe", "lon": 4.67, "lat": 50.64, "shape": "056"},
  {"name": "Austria", "code": "at", "level": "medium", "capital": "Vienna", "continent": "Europe", "lon": 14.0, "lat": 48.0, "shape": "040"},
  {"name": "Denmark", "code": "dk", "level": "medium", "capital": "Copenhagen", "continent": "Europe", "lon": 10.0, "lat": 56.0, "shape": "208"},
  {"name": "Finland", "code": "fi", "level": "medium", "capital": "Helsinki", "continent": "Europe", "lon": 27.0, "lat": 65.0, "shape": "246"},
  {"name": "Czech Republic", "code": "cz", "level": "medium", "capital": "Prague", "continent": "Europe", "lon": 15.0, "lat": 50.0, "shape": "203"},
  {"name": "Romania", "code": "ro", "level": "medium", "capital": "Bucharest", "continent": "Europe", "lon": 25.0, "lat": 46.0, "shape": "642"},
  {"name": "Hungary", "code": "hu", "level": "medium", "capital": "Budapest", "continent": "Europe", "lon": 19.0, "lat": 47.0, "shape": "348"},
  {"name": "Croatia", "code": "hr", "level": "medium", "capital": "Zagreb", "continent": "Europe", "lon": 15.47, "lat": 45.25, "shape": "191"},
  {"name": "Serbia", "code": "rs", "level": "medium", "capital": "Belgrade", "continent": "Europe", "lon": 20.93, "lat": 43.95, "shape": "688"},
  {"name": "Pakistan", "code": "pk", "level": "medium", "capital": "Islamabad", "continent": "Asia", "lon": 71.0, "lat": 30.0, "shape": "586"},
  {"name": "Bangladesh", "code": "bd", "level": "medium", "capital": "Dhaka", "continent": "Asia", "lon": 89.87, "lat": 24.02, "shape": "050"},
  {"name": "Thailand", "code": "th", "level": "medium", "capital": "Bangkok", "continent": "Asia", "lon": 101.0, "lat": 14.0, "shape": "764"},
  {"name": "Indonesia", "code": "id", "level": "medium", "capital": "Jakarta", "continent": "Asia", "lon": 118.0, "lat": -2.0, "shape": "360"},
  {"name": "Malaysia", "code": "my", "level": "medium", "capital": "Kuala Lumpur", "continent": "Asia", "lon": 102.31, "lat": 3.78, "shape": "458"},
  {"name": "Philippines", "code": "ph", "level": "medium", "capital": "Manila", "continent": "Asia", "lon": 123.0, "lat": 12.0, "shape": "608"},
  {"name": "Vietnam", "code": "vn", "level": "medium", "capital": "Hanoi", "continent": "Asia", "lon": 108.0, "lat": 16.0, "shape": "704"},
  {"name": "Iran", "code": "ir", "level": "medium", "capital": "Tehran", "continent": "Asia", "lon": 53.0, "lat": 32.0, "shape": "364"},
  {"name": "Iraq", "code": "iq", "level": "medium", "capital": "Baghdad", "continent": "Asia", "lon": 43.0, "lat": 33.0, "shape": "368"},
  {"name": "Morocco", "code": "ma", "level": "medium", "capital": "Rabat", "continent": "Africa", "lon": -6.0, "lat": 32.0, "shape": "504"},
  {"name": "Algeria", "code": "dz", "level": "medium", "capital": "Algiers", "continent": "Africa", "lon": 1.0, "lat": 28.0, "shape": "012"},
  {"name": "Kenya", "code": "ke", "level": "medium", "capital": "Nairobi", "continent": "Africa", "lon": 38.0, "lat": 0.1, "shape": "404"},
  {"name": "Ethiopia", "code": "et", "level": "medium", "capital": "Addis Ababa", "continent": "Africa", "lon": 40.0, "lat": 9.0, "shape": "231"},
  {"name": "Ghana", "code": "gh", "level": "medium", "capital": "Accra", "continent": "Africa", "lon": -1.02, "lat": 7.95, "shape": "288"},
  {"name": "Colombia", "code": "co", "level": "medium", "capital": "Bogotá", "continent": "South America", "lon": -73.25, "lat": 4.0, "shape": "170"},
  {"name": "Chile", "code": "cl", "level": "medium", "capital": "Santiago", "continent": "South America", "lon": -71.0, "lat": -33.0, "shape": "152"},
  {"name": "Peru", "code": "pe", "level": "medium", "capital": "Lima", "continent": "South America", "lon": -76.0, "lat": -9.4, "shape": "604"},
  {"name": "Venezuela", "code": "ve", "level": "medium", "capital": "Caracas", "continent": "South America", "lon": -67.0, "lat": 8.0, "shape": "862"},
  {"name": "Ireland", "code": "ie", "level": "medium", "capital": "Dublin", "continent": "Europe", "lon": -8.0, "lat": 53.0, "shape": "372"},
  {"name": "Luxembourg", "code": "lu", "level": "hard", "capital": "Luxembourg", "continent": "Europe", "lon": 6.13, "lat": 49.77, "shape": "442"},
  {"name": "Iceland", "code": "is", "level": "hard", "capital": "Reykjavík", "continent": "Europe", "lon": -19.0, "lat": 65.0, "shape": "352"},
  {"name": "Lithuania", "code": "lt", "level": "hard", "capital": "Vilnius", "continent": "Europe", "lon": 24.0, "lat": 55.2, "shape": "440"},
  {"name": "Latvia", "code": "lv", "level": "hard", "capital": "Riga", "continent": "Europe", "lon": 25.0, "lat": 57.0, "shape": "428"},
  {"name": "Estonia", "code": "ee", "level": "hard", "capital": "Tallinn", "continent": "Europe", "lon": 26.0, "lat": 59.0, "shape": "233"},
  {"name": "Slovenia", "code": "si", "level": "hard", "capital": "Ljubljana", "continent": "Europe", "lon": 15.0, "lat": 46.0, "shape": "705"},
  {"name": "Slovakia", "code": "sk", "level": "hard", "capital": "Bratislava", "continent": "Europe", "lon": 19.7, "lat": 48.7, "shape": "703"},
  {"name": "Bulgaria", "code": "bg", "level": "hard", "capital": "Sofia", "continent": "Europe", "lon": 25.5, "lat": 42.75, "shape": "100"},
  {"name": "Moldova", "code": "md", "level": "hard", "capital": "Chișinău", "continent": "Europe", "lon": 28.52, "lat": 47.25, "shape": "498"},
  {"name": "Belarus", "code": "by", "level": "hard", "capital": "Minsk", "continent": "Europe", "lon": 28.05, "lat": 53.53, "shape": "112"},
  {"name": "Georgia", "code": "ge", "level": "hard", "capital": "Tbilisi", "continent": "Europe", "lon": 44.0, "lat": 42.0, "shape": "268"},
  {"name": "Armenia", "code": "am", "level": "hard", "capital": "Yerevan", "continent": "Asia", "lon": 44.95, "lat": 40.38, "shape": "051"},
  {"name": "Azerbaijan", "code": "az", "level": "hard", "capital": "Baku", "continent": "Asia", "lon": 47.7, "lat": 40.3, "shape": "031"},
  {"name": "Kazakhstan", "code": "kz", "level": "hard", "capital": "Astana", "continent": "Asia", "lon": 68.0, "lat": 48.0, "shape": "398"},
  {"name": "Uzbekistan", "code": "uz", "level": "hard", "capital": "Tashkent", "continent": "Asia", "lon": 66.0, "lat": 41.0, "shape": "860"},
  {"name": "Kyrgyzstan", "code": "kg", "level": "hard", "capital": "Bishkek", "continent": "Asia", "lon": 75.0, "lat": 41.0, "shape": "417"},
  {"name": "Tajikistan", "code": "tj", "level": "hard", "capital": "Dushanbe", "continent": "Asia", "lon": 71.37, "lat": 38.58, "shape": "762"},
  {"name": "Turkmenistan", "code": "tm", "level": "hard", "capital": "Ashgabat", "continent": "Asia", "lon": 60.0, "lat": 39.0, "shape": "795"},
  {"name": "Mongolia", "code": "mn", "level": "hard", "capital": "Ulaanbaatar", "continent": "Asia", "lon": 105.0, "lat": 46.0, "shape": "496"},
  {"name": "Nepal", "code": "np", "level": "hard", "capital": "Kathmandu", "continent": "Asia", "lon": 84.0, "lat": 28.0, "shape": "524"},
  {"name": "Sri Lanka", "code": "lk", "level": "hard", "capital": "Sri Jayawardenepura Kotte", "continent": "Asia", "lon": 81.0, "lat": 7.0, "shape": "144"},
  {"name": "Myanmar", "code": "mm", "level": "hard", "capital": "Naypyidaw", "continent": "Asia", "lon": 96.0, "lat": 22.0, "shape": "104"},
  {"name": "Cambodia", "code": "kh", "level": "hard", "capital": "Phnom Penh", "continent": "Asia", "lon": 105.0, "lat": 12.5, "shape": "116"},
  {"name": "Laos", "code": "la", "level": "hard", "capital": "Vientiane", "continent": "Asia", "lon": 104.1, "lat": 18.2, "shape": "418"},
  {"name": "Bhutan", "code": "bt", "level": "hard", "capital": "Thimphu", "continent": "Asia", "lon": 90.5, "lat": 27.45, "shape": "064"},
  {"name": "Maldives", "code": "mv", "level": "hard", "capital": "Malé", "continent": "Asia", "lon": 73.51, "lat": 4.18, "shape": "462"},
  {"name": "Singapore", "code": "sg", "level": "hard", "capital": "Singapore", "continent": "Asia", "lon": 103.8, "lat": 1.3, "shape": "702"},
  {"name": "Brunei", "code": "bn", "level": "hard", "capital": "Bandar Seri Begawan", "continent": "Asia", "lon": 114.57, "lat": 4.4, "shape": "096"},
  {"name": "East Timor", "code": "tl", "level": "hard", "capital": "Dili", "continent": "Asia", "lon": 125.75, "lat": -8.97, "shape": "626"},
  {"name": "Papua New Guinea", "code": "pg", "level": "hard", "capital": "Port Moresby", "continent": "Oceania", "lon": 147.0, "lat": -6.3, "shape": "598"},
  {"name": "Fiji", "code": "fj", "level": "hard", "capital": "Suva", "continent": "Oceania", "lon": 178.0, "lat": -18.0, "shape": "242"},
  {"name": "Vanuatu", "code": "vu", "level": "hard", "capital": "Port Vila", "continent": "Oceania", "lon": 168.02, "lat": -16.63, "shape": "548"},
  {"name": "Samoa", "code": "ws", "level": "hard", "capital": "Apia", "continent": "Oceania", "lon": -172.22, "lat": -13.74, "shape": "882"},
  {"name": "Tonga", "code": "to", "level": "hard", "capital": "Nukuʻalofa", "continent": "Oceania", "lon": -174.81, "lat": -20.59, "shape": "776"},
  {"name": "Kiribati", "code": "ki", "level": "hard", "capital": "South Tarawa", "continent": "Oceania", "lon": 173.03, "lat": 1.47, "shape": "296"},
  {"name": "Jordan", "code": "jo", "level": "hard", "capital": "Amman", "continent": "Asia", "lon": 36.5, "lat": 31.2, "shape": "400"},
  {"name": "Lebanon", "code": "lb", "level": "hard", "capital": "Beirut", "continent": "Asia", "lon": 35.77, "lat": 33.83, "shape": "422"},
  {"name": "Syria", "code": "sy", "level": "hard", "capital": "Damascus", "continent": "Asia", "lon": 38.58, "lat": 35.22, "shape": "760"},
  {"name": "Yemen", "code": "ye", "level": "hard", "capital": "Sanaa", "continent": "Asia", "lon": 48.0, "lat": 15.5, "shape": "887"},
  {"name": "Oman", "code": "om", "level": "hard", "capital": "Muscat", "continent": "Asia", "lon": 57.0, "lat": 21.0, "shape": "512"},
  {"name": "Kuwait", "code": "kw", "level": "hard", "capital": "Kuwait City", "continent": "Asia", "lon": 47.6, "lat": 29.17, "shape": "414"},
  {"name": "Qatar", "code": "qa", "level": "hard", "capital": "Doha", "continent": "Asia", "lon": 51.21, "lat": 25.27, "shape": "634"},
  {"name": "Bahrain", "code": "bh", "level": "hard", "capital": "Manama", "continent": "Asia", "lon": 50.55, "lat": 26.07, "shape": "048"},
  {"name": "UAE", "code": "ae", "level": "hard", "capital": "Abu Dhabi", "continent": "Asia", "lon": 54.3, "lat": 24.4, "shape": "784"},
  {"name": "Libya", "code": "ly", "level": "hard", "capital": "Tripoli", "continent": "Africa", "lon": 17.0, "lat": 27.0, "shape": "434"},
  {"name": "Tunisia", "code": "tn", "level": "hard", "capital": "Tunis", "continent": "Africa", "lon": 10.0, "lat": 34.0, "shape": "788"},
  {"name": "Sudan", "code": "sd", "level": "hard", "capital": "Khartoum", "continent": "Africa", "lon": 32.0, "lat": 15.0, "shape": "729"},
  {"name": "Tanzania", "code": "tz", "level": "hard", "capital": "Dodoma", "continent": "Africa", "lon": 34.85, "lat": -6.31, "shape": "834"},
  {"name": "Uganda", "code": "ug", "level": "hard", "capital": "Kampala", "continent": "Africa", "lon": 32.39, "lat": 1.28, "shape": "800"},
  {"name": "Zimbabwe", "code": "zw", "level": "hard", "capital": "Harare", "continent": "Africa", "lon": 30.0, "lat": -19.0, "shape": "716"},
  {"name": "Zambia", "code": "zm", "level": "hard", "capital": "Lusaka", "continent": "Africa", "lon": 28.0, "lat": -14.0, "shape": "894"},
  {"name": "Mozambique", "code": "mz", "level": "hard", "capital": "Maputo", "continent": "Africa", "lon": 35.0, "lat": -19.0, "shape": "508"},
  {"name": "Madagascar", "code": "mg", "level": "hard", "capital": "Antananarivo", "continent": "Africa", "lon": 47.0, "lat": -20.0, "shape": "450"},
  {"name": "Cameroon", "code": "cm", "level": "hard", "capital": "Yaoundé", "continent": "Africa", "lon": 12.65, "lat": 5.13, "shape": "120"},
  {"name": "Senegal", "code": "sn", "level": "hard", "capital": "Dakar", "continent": "Africa", "lon": -14.28, "lat": 14.37, "shape": "686"},
  {"name": "Ivory Coast", "code": "ci", "level": "hard", "capital": "Yamoussoukro", "continent": "Africa", "lon": -6.0, "lat": 8.0, "shape": "384"},
  {"name": "Uruguay", "code": "uy", "level": "hard", "capital": "Montevideo", "continent": "South America", "lon": -56.0, "lat": -33.0, "shape": "858"},
  {"name": "Paraguay", "code": "py", "level": "hard", "capital": "Asunción", "continent": "South America", "lon": -58.0, "lat": -23.5, "shape": "600"},
  {"name": "Bolivia", "code": "bo", "level": "hard", "capital": "La Paz and Sucre", "continent": "South America", "lon": -64.99, "lat": -17.06, "shape": "068"},
  {"name": "Ecuador", "code": "ec", "level": "hard", "capital": "Quito", "continent": "South America", "lon": -78.0, "lat": -1.0, "shape": "218"},
  {"name": "Panama", "code": "pa", "level": "hard", "capital": "Panama City", "continent": "North America", "lon": -80.37, "lat": 8.62, "shape": "591"},
  {"name": "Costa Rica", "code": "cr", "level": "hard", "capital": "San José", "continent": "North America", "lon": -84.0, "lat": 10.0, "shape": "188"},
  {"name": "Guatemala", "code": "gt", "level": "hard", "capital": "Guatemala City", "continent": "North America", "lon": -90.25, "lat": 15.5, "shape": "320"},
  {"name": "Honduras", "code": "hn", "level": "hard", "capital": "Tegucigalpa", "continent": "North America", "lon": -86.82, "lat": 14.63, "shape": "340"},
  {"name": "El Salvador", "code": "sv", "level": "hard", "capital": "San Salvador", "continent": "North America", "lon": -88.87, "lat": 13.67, "shape": "222"},
  {"name": "Nicaragua", "code": "ni", "level": "hard", "capital": "Managua", "continent": "North America", "lon": -85.0, "lat": 13.0, "shape": "558"},
  {"name": "Jamaica", "code": "jm", "level": "hard", "capital": "Kingston", "continent": "North America", "lon": -77.4, "lat": 18.18, "shape": "388"},
  {"name": "Haiti", "code": "ht", "level": "hard", "capital": "Port-au-Prince", "continent": "North America", "lon": -72.8, "lat": 19.0, "shape": "332"},
  {"name": "Dominican Republic", "code": "do", "level": "hard", "capital": "Santo Domingo", "continent": "North America", "lon": -70.2, "lat": 18.8, "shape": "214"},
  {"name": "Trinidad & Tobago", "code": "tt", "level": "hard", "capital": "Port of Spain", "continent": "North America", "lon": -61.52, "lat": 10.67, "shape": "780"},
  {"name": "Barbados", "code": "bb", "level": "hard", "capital": "Bridgetown", "continent": "North America", "lon": -59.55, "lat": 13.17, "shape": "052"},
  {"name": "Malta", "code": "mt", "level": "hard", "capital": "Valletta", "continent": "Europe", "lon": 14.4, "lat": 35.9, "shape": "470"},
  {"name": "Cyprus", "code": "cy", "level": "hard", "capital": "Nicosia", "continent": "Europe", "lon": 33.0, "lat": 35.0, "shape": "196"},
  {"name": "Albania", "code": "al", "level": "hard", "capital": "Tirana", "continent": "Europe", "lon": 20.0, "lat": 41.0, "shape": "008"},
  {"name": "North Macedonia", "code": "mk", "level": "hard", "capital": "Skopje", "continent": "Europe", "lon": 21.72, "lat": 41.65, "shape": "807"},
  {"name": "Bosnia", "code": "ba", "level": "hard", "capital": "Sarajevo", "continent": "Europe", "lon": 18.0, "lat": 44.0, "shape": "070"},
  {"name": "Montenegro", "code": "me", "level": "hard", "capital": "Podgorica", "continent": "Europe", "lon": 19.22, "lat": 42.77, "shape": "499"},
  {"name": "Kosovo", "code": "xk", "level": "hard", "capital": "Pristina", "continent": "Europe", "lon": 20.83, "lat": 42.55, "shape": "Kosovo"},
];
